# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='status',
            field=models.CharField(choices=[(b'A', b'assigned'), (b'F', b'finished')], default=b'A', max_length=1),
        ),
        migrations.AlterField(
            model_name='recipientneed',
            name='status',
            field=models.CharField(choices=[(b'REQ', b'requested'), (b'PEN', b'pending'), (b'REC', b'received')], default=b'REQ', max_length=3),
        ),
    ]
