# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_recipientneed_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientneed',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
