# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-26 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_recipientneed_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='needs',
        ),
    ]
